# Generated by Django 3.2.25 on 2024-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
